### ISSUE TITLE
Images in resource description overflow container

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/dthm4kaiako#426]
![image](https://user-images.githubusercontent.com/8001048/63211509-44f39480-c14c-11e9-979e-4457ba44a5d9.png)

This may fix it:

```css
img {
    max-width: 100%;
    height: auto;
}
```
